### ISSUE TITLE
nifi upgrade

### ISSUE THREAD

**Issue by yossisht9876** [Orange-OpenSource/nifikop#161] opened 2021-11-17 13:05 UTC
## Bug Report

**What did you do?**
trying to upgrade nifi image to 1.14.0 failed
the pods keep restating every few sec

i have nifikop 0.7.2

cert manger 1.5.3 (upgraded from 1.2.0)

secure cluster

if i change the image to 1.13.2 and it works its works

i  saw in the logs that nifikop cant connect to the nifi nodes.

**Comment by riccardo-salamanna** [comment] 2021-11-17 13:13
duplicate of #141 - there's no support as of now for 1.14 👍  hope it helps

**Comment by michael81877** [comment] 2021-11-18 12:05
You can provide a value for `nifi.sensitive.props.key` and nifi 1.14.0 and 1.15.0 both work. I've run them both.

https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#security_properties

**Comment by yossisht9876** [comment] 2021-11-20 20:42
thanks but it not working for me, i think cert manger related to it.
i can ssh to the pods for a few seconds and i can see that the flow.xml file isn't crested so it keep restarting.

**Closed** 2021-11-29 10:00 UTC
